version: '3.8'
services:

  app:
    build:
      context: .
    image: netyeti/toolbox:latest
    environment:
      - TESTVAR=${TESTVAR:-test1}
    stdin_open: true
    tty: true
    command: ["/bin/zsh"]
    volumes:
      - /:/host
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"
    
