version: '3.8'
services:

  app:
    build:
      context: .
    environment:
      - TESTVAR=test1
    #command: ["/app/testfile"]
    volumes:
      - /:/host
      - /var/run/docker.sock:/var/run/docker.sock
      - ./src:/app
    